import { Project, StrategyDoc, ADR, OpenItem, Deliverable, ActivityEvent } from './types';

export const initialProjects: Project[] = [
  {
    id: 'proj-mohawk',
    name: 'Mohawk Project Hub',
    key: 'MHK',
    description: 'Primary strategic hub for cross-functional collaboration, Google Drive assets, and Agentic AI execution.',
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date().toISOString(),
    status: 'active',
    accentColor: '#0284c7', // Sky
  },
  {
    id: 'proj-brand',
    name: 'Brand Refresh & Design System',
    key: 'BND',
    description: 'Initiative to modernize brand guidelines, vector logo assets, and shared presentation templates.',
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date().toISOString(),
    status: 'active',
    accentColor: '#10b981', // Emerald
  },
];

export function createBlankStrategy(projectId: string, projectName = 'New Project'): StrategyDoc {
  return {
    id: `strategy-${projectId}`,
    projectId,
    mission: `Define the core mission and strategic direction for ${projectName}.`,
    vision: `Outline the long-term vision, target market, and value proposition for ${projectName}.`,
    targetAudience: 'Early adopters, core customers, and internal stakeholders.',
    pillars: [
      {
        id: `pillar-${Date.now()}-1`,
        title: 'Core Milestone 1',
        description: 'Define key deliverables and architectural goals.',
        metrics: '100% completion of foundational specs.',
        targetDate: 'Q4 2026',
      },
    ],
    brandGuidelines: {
      primaryColor: '#0284c7',
      secondaryColor: '#4f46e5',
      accentColor: '#10b981',
      fontFamily: 'Inter / Plus Jakarta Sans',
      toneOfVoice: 'Clear, modern, and execution-oriented.',
      driveBrandKitUrl: '',
    },
    brandAssets: [],
    updatedAt: new Date().toISOString(),
  };
}

export const initialStrategy: StrategyDoc = {
  id: 'strategy-proj-mohawk',
  projectId: 'proj-mohawk',
  mission: 'Empower small cross-functional teams and autonomous AI agents to ship cohesive, high-impact products with zero friction.',
  vision: 'A unified collaboration cockpit where human strategic intent seamlessly orchestrates agentic AI execution and Google Drive deliverables.',
  targetAudience: 'High-leverage agile startup teams, product innovators, and AI-augmented technical leaders.',
  pillars: [
    {
      id: 'pillar-1',
      title: 'Autonomous AI Delivery',
      description: 'Equip agentic AI partners with structured contexts, API endpoints, and direct Google Drive access to generate deliverables autonomously.',
      metrics: '80% of routine technical memos and draft specs produced and updated by agents.',
      targetDate: 'Q4 2026',
    },
    {
      id: 'pillar-2',
      title: 'Real-Time Transparency & Slack Velocity',
      description: 'Eliminate status meetings by publishing async activity streams directly to team Slack channels with full auditability.',
      metrics: '< 15 min response time on blocked items and immediate ADR visibility.',
      targetDate: 'Q4 2026',
    },
    {
      id: 'pillar-3',
      title: 'Frictionless Document & Asset Hub',
      description: 'Single source of truth linking Google Drive assets, design mockups, and living markdown specs.',
      metrics: 'Zero missing or outdated project artifacts across sprints.',
      targetDate: 'Q1 2027',
    },
  ],
  brandGuidelines: {
    primaryColor: '#0284c7',
    secondaryColor: '#4f46e5',
    accentColor: '#10b981',
    fontFamily: 'Inter / Plus Jakarta Sans',
    toneOfVoice: 'Decisive, modern, transparent, and execution-oriented.',
    driveBrandKitUrl: 'https://drive.google.com/',
  },
  brandAssets: [
    {
      id: 'asset-1',
      name: 'Primary Wordmark & Logo (SVG)',
      type: 'logo',
      driveUrl: 'https://drive.google.com/',
      notes: 'Master vector files in Google Drive Brand Kit folder.',
    },
    {
      id: 'asset-2',
      name: 'Design System & Token Specs',
      type: 'guideline',
      driveUrl: 'https://drive.google.com/',
      notes: 'Color palettes, elevation curves, typography scales.',
    },
  ],
  updatedAt: new Date().toISOString(),
};

export const initialADRs: ADR[] = [
  {
    id: 'adr-001',
    projectId: 'proj-mohawk',
    number: 1,
    title: 'Deploy Collaboration Hub on Google Cloud Run with Serverless Firestore',
    status: 'accepted',
    subsystem: 'devops',
    context: 'We need a scalable, maintenance-free hosting architecture for a small team collaboration hub that stays within Google Cloud\'s free tier allowances.',
    decision: 'Containerize Next.js with standalone output and deploy on Google Cloud Run with Firestore in Native mode. Scale-to-zero when idle, 2M free requests/mo.',
    consequences: 'Zero infrastructure cost under normal team usage. Fast cold starts (<1.5s). Requires containerized builds.',
    alternativesConsidered: 'Cloud SQL (high base cost ~$15-30/mo), GKE (overkill complexity for small team), VM Compute Engine (manual ops).',
    author: 'Architecture Lead',
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: 'adr-002',
    projectId: 'proj-mohawk',
    number: 2,
    title: 'Hybrid Google Drive Integration Model',
    status: 'accepted',
    subsystem: 'backend',
    context: 'Team members create and review Google Docs/Sheets, while AI agents produce deliverables programmatically.',
    decision: 'Adopt a hybrid approach: Use the Google Drive Picker API on the web UI for team members, and a Google Cloud Service Account for AI agent automated uploads.',
    consequences: 'Team maintains granular access controls; AI agents can push deliverables without individual user token refreshes.',
    alternativesConsidered: 'Client-side OAuth only (agents cannot write asynchronously), Service Account only (users cannot easily browse private team folders).',
    author: 'AI Integrations Lead',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'adr-003',
    projectId: 'proj-mohawk',
    number: 3,
    title: 'Bi-directional Slack Webhooks and Secured Agent REST API',
    status: 'accepted',
    subsystem: 'ai-agents',
    context: 'The team works primarily in Slack, while autonomous agents need a standardized API to query context and post deliverables.',
    decision: 'Implement outgoing Slack incoming webhooks for status notifications and expose a REST API at /api/v1/agent/* secured via API Key for agentic partners.',
    consequences: 'Immediate team awareness in Slack; external agents can be written in any language/runtime (Python, Node, AGY).',
    alternativesConsidered: 'Full Slack Socket Mode bot (requires persistent background process), Polling via email.',
    author: 'Team Lead',
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
];

export const initialOpenItems: OpenItem[] = [
  {
    id: 'item-1',
    projectId: 'proj-mohawk',
    title: 'Configure Google Cloud Run service and map custom domain',
    description: 'Create Cloud Run service in us-central1, configure environment variables, and map DNS record.',
    status: 'in-progress',
    priority: 'urgent',
    owner: 'DevOps / Lead',
    dueDate: '2026-09-22',
    tags: ['infra', 'cloud-run', 'gcp'],
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: 'item-2',
    projectId: 'proj-mohawk',
    title: 'Set up Google Cloud Service Account with Drive write permissions',
    description: 'Enable Google Drive API in GCP console, create service account key, and share team Drive folder.',
    status: 'todo',
    priority: 'high',
    owner: 'DevOps',
    dueDate: '2026-09-25',
    tags: ['gdrive', 'security', 'auth'],
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: 'item-3',
    projectId: 'proj-mohawk',
    title: 'Connect Slack Incoming Webhook for #project-pulse channel',
    description: 'Create incoming webhook URL in Slack App settings and add SLACK_WEBHOOK_URL to environment.',
    status: 'todo',
    priority: 'medium',
    owner: 'Product Lead',
    dueDate: '2026-09-24',
    tags: ['slack', 'notifications'],
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'item-4',
    projectId: 'proj-mohawk',
    title: 'Review Brand Voice & Tone guidelines with Stakeholders',
    description: 'Align team on copy principles and sign off on primary brand palette in Strategy Canvas.',
    status: 'done',
    priority: 'medium',
    owner: 'Design Lead',
    dueDate: '2026-09-15',
    tags: ['branding', 'strategy'],
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
];

export const initialDeliverables: Deliverable[] = [
  {
    id: 'del-1',
    projectId: 'proj-mohawk',
    title: 'Q4 Product Strategy & Architecture Specification',
    summary: 'Executive brief outlining core pillars, system architecture, and Agentic AI collaboration flows.',
    type: 'google-doc',
    driveUrl: 'https://docs.google.com/',
    author: 'AI Agent: Architect',
    authorType: 'agent',
    tags: ['strategy', 'architecture', 'v1'],
    linkedItemId: 'item-1',
    markdownContent: `### Executive Overview\nThis specification details the transition to a serverless project hub powered by Google Cloud Run and Firestore.\n\n#### Key Objectives\n1. Zero-maintenance infrastructure with free tier cost ceiling.\n2. Native integration with Google Drive and Slack.\n3. Turnkey API for external autonomous coding agents.`,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'del-2',
    projectId: 'proj-mohawk',
    title: 'Team Brand Kit & Asset Directory',
    summary: 'Centralized Google Drive folder containing SVG wordmarks, typography guidelines, and social cards.',
    type: 'drive-folder',
    driveUrl: 'https://drive.google.com/',
    author: 'Design Lead',
    authorType: 'user',
    tags: ['branding', 'design', 'assets'],
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
];

export const initialActivities: ActivityEvent[] = [
  {
    id: 'act-1',
    projectId: 'proj-mohawk',
    timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    actor: { name: 'AI Partner: Overseer', type: 'agent' },
    action: 'Generated Deliverable Spec',
    details: 'Published Q4 Product Strategy & Architecture Specification to Deliverables Hub.',
    category: 'deliverable',
    link: '/deliverables',
  },
  {
    id: 'act-2',
    projectId: 'proj-mohawk',
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    actor: { name: 'DevOps / Lead', type: 'user' },
    action: 'Updated Open Item',
    details: 'Moved "Configure Google Cloud Run service" to In Progress.',
    category: 'item',
    link: '/open-items',
  },
  {
    id: 'act-3',
    projectId: 'proj-mohawk',
    timestamp: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    actor: { name: 'Architecture Lead', type: 'user' },
    action: 'Recorded ADR #003',
    details: 'Bi-directional Slack Webhooks and Secured Agent REST API accepted.',
    category: 'adr',
    link: '/decisions',
  },
];
